name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build the website
        run: deno run -A --unstable build_website.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vale"
          entrypoint: "./website.ts"